"""
ULPF Parser Specification Validator.

Validates parser specifications generated by the local AI model
before they are allowed to enter the parser registry or be executed.
Ensures the LLM is never trusted as an authority.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List, Optional

from app.normalization.field_mapping import COMMON_FIELD_MAP


ALLOWED_PARSER_TYPES = {
    "key_value",
    "delimited",
    "regex",
    "json",
    "syslog",
    "csv",
    "xml",
}

ALLOWED_FIELD_TYPES = {
    "datetime",
    "ip",
    "port",
    "protocol",
    "action",
    "number",
    "string",
}


def validate_parser_spec(
    parser_spec: Dict[str, Any],
    log_samples: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Validate an AI-generated parser specification against strict schema,
    structural evidence, and hallucination rules.

    Args:
        parser_spec: Parser specification dictionary to validate.
        log_samples: Optional raw log samples to check for hallucinated fields / impossible delimiters.

    Returns:
        {
            "valid": True/False,
            "errors": [...]
        }
    """
    errors: List[str] = []

    if not isinstance(parser_spec, dict):
        return {
            "valid": False,
            "errors": ["Parser specification must be a dictionary."],
        }

    # 1. Check required format name
    format_name = parser_spec.get("format_name")
    if (
        not format_name
        or not isinstance(format_name, str)
        or not format_name.strip()
        or format_name.strip().lower() in ("unknown", "null", "none", "generic")
    ):
        errors.append("Missing or invalid required 'format_name'.")

    # 2. Check parser type
    parser_type = parser_spec.get("parser_type")
    if parser_type not in ALLOWED_PARSER_TYPES:
        errors.append(f"Invalid parser_type: '{parser_type}'. Allowed: {sorted(ALLOWED_PARSER_TYPES)}")

    # 3. Check delimiter constraints
    if parser_type in ("delimited", "csv"):
        delimiter = parser_spec.get("delimiter")
        if not delimiter or not isinstance(delimiter, str):
            errors.append(f"Missing required 'delimiter' for parser_type '{parser_type}'.")
        else:
            # Impossible delimiter: alphanumeric characters are invalid as structured log delimiters
            if delimiter.isalnum():
                errors.append(
                    f"Impossible delimiter '{delimiter}': delimiters must be non-alphanumeric separator characters."
                )
            # If log samples provided, verify delimiter actually exists in the sample lines
            elif log_samples:
                sample_lines = [l.strip() for l in log_samples.splitlines() if l.strip()]
                if sample_lines and not any(delimiter in line for line in sample_lines):
                    errors.append(
                        f"Impossible delimiter '{delimiter}': delimiter does not appear anywhere in sample logs."
                    )

    # 4. Check key=value separator
    if parser_type == "key_value":
        kv_sep = parser_spec.get("key_value_separator")
        if kv_sep and kv_sep not in ("=", ":"):
            errors.append(f"Invalid key_value_separator: '{kv_sep}'. Allowed: '=' or ':'.")

    # 5. Check regex pattern syntax
    if parser_type == "regex":
        pattern = parser_spec.get("regex_pattern") or parser_spec.get("pattern_regex")
        if not pattern or not str(pattern).strip():
            errors.append("Missing required 'regex_pattern' for parser_type 'regex'.")
        else:
            try:
                re.compile(pattern)
            except re.error as re_err:
                errors.append(f"Invalid regex_pattern syntax: {re_err}")

    # 6. Check fields
    fields = parser_spec.get("fields")
    if not isinstance(fields, list) or len(fields) == 0:
        errors.append("fields must be a non-empty list of field objects.")
        fields = []

    field_names = set()

    for index, field in enumerate(fields):
        if not isinstance(field, dict):
            errors.append(f"Field at index {index} must be an object.")
            continue

        name = field.get("name")
        field_type = field.get("type")

        if not name:
            errors.append(f"Field at index {index} is missing a name.")
            continue

        name = str(name).strip().lower()

        if name in field_names:
            errors.append(f"Duplicate field name: '{name}'.")

        field_names.add(name)

        if str(field_type).strip().lower() not in ALLOWED_FIELD_TYPES:
            errors.append(
                f"Invalid type '{field_type}' for field '{name}'. Allowed types: {sorted(ALLOWED_FIELD_TYPES)}"
            )

    # 7. Check timestamp field
    timestamp_field = parser_spec.get("timestamp_field", "")
    if timestamp_field:
        timestamp_field = str(timestamp_field).strip().lower()
        if timestamp_field not in field_names:
            errors.append(f"timestamp_field '{timestamp_field}' does not exist in declared fields.")
        else:
            timestamp_type = None
            for field in fields:
                if (
                    isinstance(field, dict)
                    and str(field.get("name", "")).strip().lower() == timestamp_field
                ):
                    timestamp_type = str(field.get("type", "")).strip().lower()
                    break

            if timestamp_type != "datetime":
                errors.append(
                    f"Timestamp field '{timestamp_field}' must have type 'datetime', but has type '{timestamp_type}'."
                )

    # 8. Check optional fields
    optional_fields = parser_spec.get("optional_fields", [])
    if not isinstance(optional_fields, list):
        errors.append("optional_fields must be a list.")
    else:
        for field_name in optional_fields:
            field_name = str(field_name).strip().lower()
            if field_name not in field_names:
                errors.append(f"Optional field '{field_name}' does not exist in declared fields.")

    # 9. Check for Hallucinated Fields against raw log samples
    if log_samples and field_names:
        sample_lines = [l.strip() for l in log_samples.splitlines() if l.strip()]
        sample_text_lower = "\n".join(sample_lines).lower()

        if parser_type in ("key_value", "logfmt"):
            # Build reverse lookup for known canonical field names
            canonical_to_synonyms: Dict[str, List[str]] = {}
            for raw_k, canon_k in COMMON_FIELD_MAP.items():
                canonical_to_synonyms.setdefault(canon_k, []).append(raw_k)

            for fname in field_names:
                # Allowed if fname appears in sample text, or is timestamp prefix, or a known synonym appears
                direct_match = (f"{fname}=" in sample_text_lower or f"{fname}:" in sample_text_lower)
                canon = COMMON_FIELD_MAP.get(fname, fname)
                synonyms = canonical_to_synonyms.get(canon, [])
                synonym_matches = [
                    syn for syn in synonyms
                    if (f"{syn}=" in sample_text_lower or f"{syn}:" in sample_text_lower)
                ]
                if not direct_match and not synonym_matches and fname != "timestamp":
                    errors.append(
                        f"Hallucinated field '{fname}': field key is not present anywhere in sample logs."
                    )

        elif parser_type in ("delimited", "csv"):
            delimiter = parser_spec.get("delimiter", "|")
            if delimiter and sample_lines:
                max_tokens = max(len(line.split(delimiter)) for line in sample_lines)
                if len(field_names) > max_tokens:
                    errors.append(
                        f"Hallucinated fields: specification defines {len(field_names)} fields, but sample logs only have {max_tokens} columns."
                    )

    return {
        "valid": len(errors) == 0,
        "errors": errors,
    }
