"""
Standard OCSF and OSSEM security event taxonomy definitions.
"""

from __future__ import annotations

from typing import Dict, Tuple

# Category name & numeric category UID
CATEGORY_MAP: Dict[str, Tuple[str, int]] = {
    "system_activity": ("System Activity", 1),
    "system": ("System Activity", 1),
    "security_finding": ("Security Finding", 2),
    "security": ("Security Finding", 2),
    "identity_and_access_management": ("Identity & Access Management", 3),
    "iam": ("Identity & Access Management", 3),
    "identity": ("Identity & Access Management", 3),
    "authentication": ("Identity & Access Management", 3),
    "network_activity": ("Network Activity", 4),
    "network": ("Network Activity", 4),
    "discovery": ("Discovery", 5),
    "application_activity": ("Application Activity", 6),
    "application": ("Application Activity", 6),
}

# Class name & class UID
CLASS_MAP: Dict[str, Tuple[str, int]] = {
    "system_activity": ("System Activity", 1000),
    "operating_system": ("Operating System", 1000),
    "file_system_activity": ("File System Activity", 1001),
    "kernel_extension_activity": ("Kernel Extension Activity", 1002),
    "kernel_activity": ("Kernel Activity", 1003),
    "memory_activity": ("Memory Activity", 1004),
    "module_activity": ("Module Activity", 1005),
    "device_activity": ("Device Activity", 1006),
    "process_activity": ("Process Activity", 1007),
    "scheduled_job_activity": ("Scheduled Job Activity", 1008),
    "security_finding": ("Security Finding", 2001),
    "vulnerability_finding": ("Vulnerability Finding", 2002),
    "compliance_finding": ("Compliance Finding", 2003),
    "detection_finding": ("Detection Finding", 2004),
    "incident_finding": ("Incident Finding", 2005),
    "account_change": ("Account Change", 3001),
    "authentication": ("Authentication", 3002),
    "authorize_session": ("Authorize Session", 3003),
    "entity_management": ("Entity Management", 3004),
    "user_access_management": ("User Access Management", 3005),
    "group_management": ("Group Management", 3006),
    "iam": ("Identity & Access Management", 3000),
    "network_activity": ("Network Activity", 4001),
    "network": ("Network Activity", 4001),
    "http_activity": ("HTTP Activity", 4002),
    "dns_activity": ("DNS Activity", 4003),
    "dhcp_activity": ("DHCP Activity", 4004),
    "rdp_activity": ("RDP Activity", 4005),
    "smb_activity": ("SMB Activity", 4006),
    "ssh_activity": ("SSH Activity", 4007),
    "ftp_activity": ("FTP Activity", 4008),
    "email_activity": ("Email Activity", 4009),
    "web_resource_access_activity": ("Web Resource Access Activity", 6001),
    "web_browsing": ("Web Resource Access Activity", 6001),
    "application_lifecycle": ("Application Lifecycle", 6002),
    "api_activity": ("API Activity", 6003),
}

# Activity name & activity ID
ACTIVITY_MAP: Dict[str, Tuple[str, int]] = {
    # Generic & System
    "log": ("Log", 1),
    "execute": ("Execute", 1),
    "schedule": ("Schedule", 1),
    "configure": ("Configure", 1),
    "sync": ("Sync", 1),
    "index": ("Index", 1),
    "input": ("Input", 1),
    "report": ("Report", 1),
    "render": ("Render", 1),
    "search": ("Search", 1),
    "query": ("Query", 1),
    "verify": ("Verify", 1),
    "update": ("Update", 1),
    # Auth
    "login": ("Logon", 1),
    "logon": ("Logon", 1),
    "logoff": ("Logoff", 2),
    "logout": ("Logoff", 2),
    "auth_failed": ("Logon", 1),
    # Network
    "open": ("Open", 1),
    "connection": ("Open", 1),
    "connect": ("Open", 1),
    "close": ("Close", 2),
    "reset": ("Reset", 3),
    "fail": ("Fail", 4),
    "refuse": ("Refuse", 5),
    "traffic": ("Traffic", 6),
    "listen": ("Listen", 7),
    "drop": ("Fail", 4),
    "deny": ("Refuse", 5),
    "block": ("Refuse", 5),
    "reject": ("Refuse", 5),
    "allow": ("Open", 1),
}

# Severity ID mapping
SEVERITY_ID_MAP: Dict[str, int] = {
    "unknown": 0,
    "informational": 1,
    "info": 1,
    "trace": 1,
    "notice": 1,
    "low": 2,
    "warning": 3,
    "medium": 3,
    "warn": 3,
    "high": 4,
    "err": 4,
    "error": 4,
    "fatal": 4,
    "critical": 5,
    "crit": 5,
    "alert": 5,
    "emerg": 5,
}

# Standardized Severity Name and ID mapping
SEVERITY_NAME_MAP: Dict[str, Tuple[str, int]] = {
    "trace": ("Informational", 1),
    "info": ("Informational", 1),
    "informational": ("Informational", 1),
    "notice": ("Informational", 1),
    "low": ("Low", 2),
    "warn": ("Medium", 3),
    "warning": ("Medium", 3),
    "medium": ("Medium", 3),
    "err": ("High", 4),
    "error": ("High", 4),
    "high": ("High", 4),
    "fatal": ("High", 4),
    "critical": ("Critical", 5),
    "crit": ("Critical", 5),
    "alert": ("Critical", 5),
    "emerg": ("Critical", 5),
}

# Status ID mapping
STATUS_ID_MAP: Dict[str, int] = {
    "unknown": 0,
    "success": 1,
    "ok": 1,
    "failure": 2,
    "fail": 2,
    "failed": 2,
    "error": 2,
    "denied": 2,
    "blocked": 2,
}

# Process / Subsystem lookup map for macOS & standard Syslog
PROCESS_TAXONOMY_MAP: Dict[str, Dict[str, Any]] = {
    "kernel": {
        "vendor": "Apple",
        "product": "macOS Kernel",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Kernel Activity",
        "class_uid": 1003,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "sandboxd": {
        "vendor": "Apple",
        "product": "App Sandbox",
        "category_name": "Security Finding",
        "category_uid": 2,
        "class_name": "Security Finding",
        "class_uid": 2001,
        "activity_name": "Deny",
        "activity_id": 5,
    },
    "com.apple.xpc.launchd": {
        "vendor": "Apple",
        "product": "launchd",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Process Activity",
        "class_uid": 1007,
        "activity_name": "Execute",
        "activity_id": 1,
    },
    "com.apple.cdscheduler": {
        "vendor": "Apple",
        "product": "CoreDuet Scheduler",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Scheduled Job Activity",
        "class_uid": 1008,
        "activity_name": "Schedule",
        "activity_id": 1,
    },
    "com.apple.cts": {
        "vendor": "Apple",
        "product": "Central Task Scheduling",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Scheduled Job Activity",
        "class_uid": 1008,
        "activity_name": "Schedule",
        "activity_id": 1,
    },
    "mdnsresponder": {
        "vendor": "Apple",
        "product": "Bonjour",
        "category_name": "Network Activity",
        "category_uid": 4,
        "class_name": "DNS Activity",
        "class_uid": 4003,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "networkd": {
        "vendor": "Apple",
        "product": "networkd",
        "category_name": "Network Activity",
        "category_uid": 4,
        "class_name": "Network Activity",
        "class_uid": 4001,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "netbiosd": {
        "vendor": "Apple",
        "product": "netbiosd",
        "category_name": "Network Activity",
        "category_uid": 4,
        "class_name": "Network Activity",
        "class_uid": 4001,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "symptomsd": {
        "vendor": "Apple",
        "product": "Symptom Analytics",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "corecaptured": {
        "vendor": "Apple",
        "product": "CoreCapture",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "configd": {
        "vendor": "Apple",
        "product": "System Configuration",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Configure",
        "activity_id": 1,
    },
    "secd": {
        "vendor": "Apple",
        "product": "Security Framework",
        "category_name": "Identity & Access Management",
        "category_uid": 3,
        "class_name": "Authentication",
        "class_uid": 3002,
        "activity_name": "Logon",
        "activity_id": 1,
    },
    "securityd": {
        "vendor": "Apple",
        "product": "Security Framework",
        "category_name": "Identity & Access Management",
        "category_uid": 3,
        "class_name": "Authentication",
        "class_uid": 3002,
        "activity_name": "Logon",
        "activity_id": 1,
    },
    "com.apple.securityserver": {
        "vendor": "Apple",
        "product": "Security Framework",
        "category_name": "Identity & Access Management",
        "category_uid": 3,
        "class_name": "Authentication",
        "class_uid": 3002,
        "activity_name": "Logon",
        "activity_id": 1,
    },
    "taskgated": {
        "vendor": "Apple",
        "product": "Task Gate",
        "category_name": "Security Finding",
        "category_uid": 2,
        "class_name": "Security Finding",
        "class_uid": 2001,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "loginwindow": {
        "vendor": "Apple",
        "product": "Login Window",
        "category_name": "Identity & Access Management",
        "category_uid": 3,
        "class_name": "Authentication",
        "class_uid": 3002,
        "activity_name": "Logon",
        "activity_id": 1,
    },
    "blued": {
        "vendor": "Apple",
        "product": "Bluetooth",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Device Activity",
        "class_uid": 1006,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "wirelessproxd": {
        "vendor": "Apple",
        "product": "Wireless Proximity",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Device Activity",
        "class_uid": 1006,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "locationd": {
        "vendor": "Apple",
        "product": "CoreLocation",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "mds": {
        "vendor": "Apple",
        "product": "Spotlight Metadata",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "File System Activity",
        "class_uid": 1001,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "mdworker": {
        "vendor": "Apple",
        "product": "Spotlight Metadata Worker",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "File System Activity",
        "class_uid": 1001,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "windowserver": {
        "vendor": "Apple",
        "product": "Window Server",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "hidd": {
        "vendor": "Apple",
        "product": "Human Interface Device Daemon",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Device Activity",
        "class_uid": 1006,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "cloudd": {
        "vendor": "Apple",
        "product": "CloudKit",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "identityservicesd": {
        "vendor": "Apple",
        "product": "Identity Services",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "imagent": {
        "vendor": "Apple",
        "product": "iMessage Agent",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "safari": {
        "vendor": "Apple",
        "product": "Safari",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Web Resource Access Activity",
        "class_uid": 6001,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "com.apple.webkit.webcontent": {
        "vendor": "Apple",
        "product": "WebKit WebContent",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Web Resource Access Activity",
        "class_uid": 6001,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "com.apple.webkit.networking": {
        "vendor": "Apple",
        "product": "WebKit Networking",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Web Resource Access Activity",
        "class_uid": 6001,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "com.apple.addressbook.contactsaccountsservice": {
        "vendor": "Apple",
        "product": "AddressBook",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "com.apple.addressbook.internetaccountsbridge": {
        "vendor": "Apple",
        "product": "AddressBook",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "addressbooksourcesync": {
        "vendor": "Apple",
        "product": "AddressBook",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "calendaragent": {
        "vendor": "Apple",
        "product": "Calendar Agent",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "com.apple.geod": {
        "vendor": "Apple",
        "product": "GeoServices",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "com.apple.ncplugin.worldclock": {
        "vendor": "Apple",
        "product": "World Clock Widget",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "com.apple.ncplugin.weather": {
        "vendor": "Apple",
        "product": "Weather Widget",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "syslogd": {
        "vendor": "Apple",
        "product": "syslogd",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "ntpd": {
        "vendor": "Apple",
        "product": "ntpd",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "sharingd": {
        "vendor": "Apple",
        "product": "AirDrop / Sharing",
        "category_name": "Network Activity",
        "category_uid": 4,
        "class_name": "Network Activity",
        "class_uid": 4001,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "usereventagent": {
        "vendor": "Apple",
        "product": "UserEventAgent",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "airplayuiagent": {
        "vendor": "Apple",
        "product": "AirPlay",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "commcenter": {
        "vendor": "Apple",
        "product": "CoreTelephony / CommCenter",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "crashreportersupporthelper": {
        "vendor": "Apple",
        "product": "CrashReporter",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "dock": {
        "vendor": "Apple",
        "product": "macOS Dock",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "iconservicesagent": {
        "vendor": "Apple",
        "product": "IconServices",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "quicklookd": {
        "vendor": "Apple",
        "product": "QuickLook",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "quicklooksatellite": {
        "vendor": "Apple",
        "product": "QuickLook Satellite",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "mail": {
        "vendor": "Apple",
        "product": "Apple Mail",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Email Activity",
        "class_uid": 4009,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "preview": {
        "vendor": "Apple",
        "product": "Preview",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "spotlightnethelper": {
        "vendor": "Apple",
        "product": "Spotlight",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "vdcassistant": {
        "vendor": "Apple",
        "product": "Video Device Assistant",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Device Activity",
        "class_uid": 1006,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "pkd": {
        "vendor": "Apple",
        "product": "PlugInKit Daemon",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Process Activity",
        "class_uid": 1007,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "scim": {
        "vendor": "Apple",
        "product": "Simplified Chinese IM",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "tcim": {
        "vendor": "Apple",
        "product": "Traditional Chinese IM",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "garcon": {
        "vendor": "Dropbox",
        "product": "Dropbox Finder Extension",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "dropbox": {
        "vendor": "Dropbox",
        "product": "Dropbox",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "googlesoftwareupdateagent": {
        "vendor": "Google",
        "product": "Google Software Update",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "google software update": {
        "vendor": "Google",
        "product": "Google Software Update",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "ksfetch": {
        "vendor": "Google",
        "product": "Keystone Fetch",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "chromeexistion": {
        "vendor": "Google",
        "product": "Google Chrome",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Web Resource Access Activity",
        "class_uid": 6001,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "qq": {
        "vendor": "Tencent",
        "product": "QQ",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "wechat": {
        "vendor": "Tencent",
        "product": "WeChat",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "neteasemusic": {
        "vendor": "NetEase",
        "product": "NetEase Cloud Music",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "gputoolsagent": {
        "vendor": "Apple",
        "product": "Xcode GPU Tools",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "bezelservices": {
        "vendor": "Apple",
        "product": "BezelServices",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "System Activity",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "cdpd": {
        "vendor": "Apple",
        "product": "CoreDisplay Policy Daemon",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Device Activity",
        "class_uid": 1006,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "google chrome": {
        "vendor": "Google",
        "product": "Google Chrome",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Web Resource Access Activity",
        "class_uid": 6001,
        "activity_name": "Traffic",
        "activity_id": 6,
    },
    "microsoft word": {
        "vendor": "Microsoft",
        "product": "Microsoft Word",
        "category_name": "Application Activity",
        "category_uid": 6,
        "class_name": "Application Lifecycle",
        "class_uid": 6002,
        "activity_name": "Log",
        "activity_id": 1,
    },
    # Common Linux / Unix daemons
    "sshd": {
        "vendor": "OpenSSH",
        "product": "sshd",
        "category_name": "Identity & Access Management",
        "category_uid": 3,
        "class_name": "Authentication",
        "class_uid": 3002,
        "activity_name": "Logon",
        "activity_id": 1,
    },
    "sudo": {
        "vendor": "Sudo",
        "product": "sudo",
        "category_name": "Identity & Access Management",
        "category_uid": 3,
        "class_name": "Authentication",
        "class_uid": 3002,
        "activity_name": "Logon",
        "activity_id": 1,
    },
    "systemd": {
        "vendor": "Linux",
        "product": "systemd",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Process Activity",
        "class_uid": 1007,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "newsyslog": {
        "vendor": "Apple",
        "product": "newsyslog",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Operating System",
        "class_uid": 1000,
        "activity_name": "Log",
        "activity_id": 1,
    },
    "cron": {
        "vendor": "Linux",
        "product": "cron",
        "category_name": "System Activity",
        "category_uid": 1,
        "class_name": "Scheduled Job Activity",
        "class_uid": 1008,
        "activity_name": "Scheduled Activity",
        "activity_id": 1,
    },
}


def resolve_process_taxonomy(process: str) -> Dict[str, Any] | None:
    """Resolve process name or subsystem to OCSF taxonomy attributes."""
    if not process:
        return None
    # Strip any parenthetical suffix like (pam_unix)
    clean_proc = process.split("(")[0].strip()
    key = clean_proc.lower()

    if key in PROCESS_TAXONOMY_MAP:
        return PROCESS_TAXONOMY_MAP[key]

    # Check first word (e.g. "BezelServices 255.10" -> "bezelservices")
    first_word = key.split()[0]
    if first_word in PROCESS_TAXONOMY_MAP:
        return PROCESS_TAXONOMY_MAP[first_word]

    # Prefix/pattern matches for Apple subsystems
    if key.startswith("com.apple."):
        return {
            "vendor": "Apple",
            "product": clean_proc,
            "category_name": "System Activity",
            "category_uid": 1,
            "class_name": "Operating System",
            "class_uid": 1000,
            "activity_name": "Log",
            "activity_id": 1,
        }

    # Fallback for macOS / Unix daemons ending in 'd'
    if key.endswith("d") and " " not in key:
        return {
            "vendor": "Apple",
            "product": clean_proc,
            "category_name": "System Activity",
            "category_uid": 1,
            "class_name": "Operating System",
            "class_uid": 1000,
            "activity_name": "Log",
            "activity_id": 1,
        }

    return None

