[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/log/*.log
    Tag          perimeter.logs

[OUTPUT]
    Name         http
    Match        perimeter.logs
    Host         127.0.0.1
    Port         8000
    URI          /upload
    Format       json
